// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealEstateAgency.Infrastructure.EfCore;

#nullable disable

namespace RealEstateAgency.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(RealEstateAgencyDbContext))]
    [Migration("20251126073259_AddData")]
    partial class AddData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RealEstateAgency.Domain.Model.Counterparty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("passport_number");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("patronymic");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("counterparties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Иван",
                            LastName = "Иванов",
                            PassportNumber = "4010 123456",
                            Patronymic = "Иванович",
                            PhoneNumber = "89030000001"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Мария",
                            LastName = "Петрова",
                            PassportNumber = "4010 123457",
                            Patronymic = "Сергеевна",
                            PhoneNumber = "89030000002"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Алексей",
                            LastName = "Сидоров",
                            PassportNumber = "4010 123458",
                            Patronymic = "Алексеевич",
                            PhoneNumber = "89030000003"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Екатерина",
                            LastName = "Кузнецова",
                            PassportNumber = "4010 123459",
                            Patronymic = "Игоревна",
                            PhoneNumber = "89030000004"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Дмитрий",
                            LastName = "Новиков",
                            PassportNumber = "4010 123460",
                            Patronymic = "Петрович",
                            PhoneNumber = "89030000005"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Ольга",
                            LastName = "Морозова",
                            PassportNumber = "4010 123461",
                            Patronymic = "Сергеевна",
                            PhoneNumber = "89030000006"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Сергей",
                            LastName = "Васильев",
                            PassportNumber = "4010 123462",
                            Patronymic = "Игоревич",
                            PhoneNumber = "89030000007"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Анастасия",
                            LastName = "Соколова",
                            PassportNumber = "4010 123463",
                            Patronymic = "Александровна",
                            PhoneNumber = "89030000008"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Никита",
                            LastName = "Лебедев",
                            PassportNumber = "4010 123464",
                            Patronymic = "Дмитриевич",
                            PhoneNumber = "89030000009"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Татьяна",
                            LastName = "Егорова",
                            PassportNumber = "4010 123465",
                            Patronymic = "Викторовна",
                            PhoneNumber = "89030000010"
                        });
                });

            modelBuilder.Entity("RealEstateAgency.Domain.Model.RealEstate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("CadastralNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cadastral_number");

                    b.Property<double?>("CeilingHeight")
                        .HasColumnType("double precision")
                        .HasColumnName("ceiling_height");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("integer")
                        .HasColumnName("floor_number");

                    b.Property<bool>("HasEncumbrances")
                        .HasColumnType("boolean")
                        .HasColumnName("has_encumbrances");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_floors");

                    b.Property<int?>("NumberOfRooms")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_rooms");

                    b.Property<int>("RealEstatePurpose")
                        .HasColumnType("integer")
                        .HasColumnName("real_estate_purpose");

                    b.Property<int>("RealEstateType")
                        .HasColumnType("integer")
                        .HasColumnName("real_estate_type");

                    b.Property<double>("TotalArea")
                        .HasColumnType("double precision")
                        .HasColumnName("total_area");

                    b.HasKey("Id");

                    b.ToTable("real_estates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ул. Ленина, д.1",
                            CadastralNumber = "77:01:0001010:001",
                            CeilingHeight = 2.7000000000000002,
                            FloorNumber = 2,
                            HasEncumbrances = false,
                            NumberOfFloors = 5,
                            NumberOfRooms = 2,
                            RealEstatePurpose = 0,
                            RealEstateType = 0,
                            TotalArea = 55.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "ул. Пушкина, д.10",
                            CadastralNumber = "77:01:0001020:002",
                            CeilingHeight = 3.0,
                            HasEncumbrances = false,
                            NumberOfFloors = 2,
                            NumberOfRooms = 5,
                            RealEstatePurpose = 0,
                            RealEstateType = 1,
                            TotalArea = 120.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "ул. Гагарина, д.5",
                            CadastralNumber = "77:01:0001030:003",
                            CeilingHeight = 2.5,
                            FloorNumber = 4,
                            HasEncumbrances = true,
                            NumberOfFloors = 9,
                            NumberOfRooms = 1,
                            RealEstatePurpose = 0,
                            RealEstateType = 2,
                            TotalArea = 18.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "пр. Мира, д.20",
                            CadastralNumber = "77:01:0001040:004",
                            CeilingHeight = 3.2000000000000002,
                            FloorNumber = 5,
                            HasEncumbrances = false,
                            NumberOfFloors = 10,
                            RealEstatePurpose = 1,
                            RealEstateType = 3,
                            TotalArea = 250.0
                        },
                        new
                        {
                            Id = 5,
                            Address = "ул. Тверская, д.15",
                            CadastralNumber = "77:01:0001050:005",
                            CeilingHeight = 3.0,
                            FloorNumber = 1,
                            HasEncumbrances = false,
                            NumberOfFloors = 1,
                            RealEstatePurpose = 1,
                            RealEstateType = 4,
                            TotalArea = 80.0
                        },
                        new
                        {
                            Id = 6,
                            Address = "дер. Лесная, уч.5",
                            CadastralNumber = "77:01:0001060:006",
                            HasEncumbrances = false,
                            NumberOfFloors = 0,
                            RealEstatePurpose = 3,
                            RealEstateType = 5,
                            TotalArea = 500.0
                        },
                        new
                        {
                            Id = 7,
                            Address = "ул. Парковая, д.7",
                            CadastralNumber = "77:01:0001070:007",
                            CeilingHeight = 2.5,
                            FloorNumber = 1,
                            HasEncumbrances = false,
                            NumberOfFloors = 1,
                            RealEstatePurpose = 4,
                            RealEstateType = 6,
                            TotalArea = 20.0
                        },
                        new
                        {
                            Id = 8,
                            Address = "ул. Чехова, д.8",
                            CadastralNumber = "77:01:0001080:008",
                            CeilingHeight = 2.7999999999999998,
                            FloorNumber = 6,
                            HasEncumbrances = true,
                            NumberOfFloors = 12,
                            NumberOfRooms = 3,
                            RealEstatePurpose = 0,
                            RealEstateType = 0,
                            TotalArea = 75.0
                        },
                        new
                        {
                            Id = 9,
                            Address = "ул. Лермонтова, д.12",
                            CadastralNumber = "77:01:0001090:009",
                            CeilingHeight = 2.8999999999999999,
                            HasEncumbrances = false,
                            NumberOfFloors = 1,
                            NumberOfRooms = 4,
                            RealEstatePurpose = 0,
                            RealEstateType = 1,
                            TotalArea = 90.0
                        },
                        new
                        {
                            Id = 10,
                            Address = "пр. Садовый, д.3",
                            CadastralNumber = "77:01:0001100:010",
                            CeilingHeight = 3.1000000000000001,
                            FloorNumber = 3,
                            HasEncumbrances = false,
                            NumberOfFloors = 5,
                            RealEstatePurpose = 1,
                            RealEstateType = 3,
                            TotalArea = 180.0
                        });
                });

            modelBuilder.Entity("RealEstateAgency.Domain.Model.RealEstateApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("ApplicationType")
                        .HasColumnType("integer")
                        .HasColumnName("application_type");

                    b.Property<int>("CounterpartyId")
                        .HasColumnType("integer")
                        .HasColumnName("counterparty_id");

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<int>("RealEstateId")
                        .HasColumnType("integer")
                        .HasColumnName("real_estate_id");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartyId");

                    b.HasIndex("RealEstateId");

                    b.ToTable("real_estate_applications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5500000m,
                            ApplicationType = 0,
                            CounterpartyId = 1,
                            DateCreated = new DateOnly(2025, 11, 16),
                            RealEstateId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 12000000m,
                            ApplicationType = 0,
                            CounterpartyId = 2,
                            DateCreated = new DateOnly(2025, 11, 6),
                            RealEstateId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1800000m,
                            ApplicationType = 0,
                            CounterpartyId = 3,
                            DateCreated = new DateOnly(2025, 11, 11),
                            RealEstateId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 25000000m,
                            ApplicationType = 1,
                            CounterpartyId = 4,
                            DateCreated = new DateOnly(2025, 11, 21),
                            RealEstateId = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 8000000m,
                            ApplicationType = 1,
                            CounterpartyId = 5,
                            DateCreated = new DateOnly(2025, 11, 14),
                            RealEstateId = 5
                        },
                        new
                        {
                            Id = 6,
                            Amount = 500000m,
                            ApplicationType = 0,
                            CounterpartyId = 6,
                            DateCreated = new DateOnly(2025, 11, 1),
                            RealEstateId = 6
                        },
                        new
                        {
                            Id = 7,
                            Amount = 200000m,
                            ApplicationType = 1,
                            CounterpartyId = 7,
                            DateCreated = new DateOnly(2025, 11, 8),
                            RealEstateId = 7
                        },
                        new
                        {
                            Id = 8,
                            Amount = 7500000m,
                            ApplicationType = 0,
                            CounterpartyId = 8,
                            DateCreated = new DateOnly(2025, 11, 24),
                            RealEstateId = 8
                        },
                        new
                        {
                            Id = 9,
                            Amount = 9000000m,
                            ApplicationType = 0,
                            CounterpartyId = 9,
                            DateCreated = new DateOnly(2025, 11, 18),
                            RealEstateId = 9
                        },
                        new
                        {
                            Id = 10,
                            Amount = 18000000m,
                            ApplicationType = 1,
                            CounterpartyId = 10,
                            DateCreated = new DateOnly(2025, 11, 25),
                            RealEstateId = 10
                        });
                });

            modelBuilder.Entity("RealEstateAgency.Domain.Model.RealEstateApplication", b =>
                {
                    b.HasOne("RealEstateAgency.Domain.Model.Counterparty", "Counterparty")
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateAgency.Domain.Model.RealEstate", "RealEstate")
                        .WithMany()
                        .HasForeignKey("RealEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counterparty");

                    b.Navigation("RealEstate");
                });
#pragma warning restore 612, 618
        }
    }
}
