// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealEstateAgency.Infrastructure.EfCore;

#nullable disable

namespace RealEstateAgency.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(RealEstateAgencyDbContext))]
    [Migration("20251126072344_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RealEstateAgency.Domain.Model.Counterparty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("passport_number");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("patronymic");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("counterparties", (string)null);
                });

            modelBuilder.Entity("RealEstateAgency.Domain.Model.RealEstate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("CadastralNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cadastral_number");

                    b.Property<double?>("CeilingHeight")
                        .HasColumnType("double precision")
                        .HasColumnName("ceiling_height");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("integer")
                        .HasColumnName("floor_number");

                    b.Property<bool>("HasEncumbrances")
                        .HasColumnType("boolean")
                        .HasColumnName("has_encumbrances");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_floors");

                    b.Property<int?>("NumberOfRooms")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_rooms");

                    b.Property<int>("RealEstatePurpose")
                        .HasColumnType("integer")
                        .HasColumnName("real_estate_purpose");

                    b.Property<int>("RealEstateType")
                        .HasColumnType("integer")
                        .HasColumnName("real_estate_type");

                    b.Property<double>("TotalArea")
                        .HasColumnType("double precision")
                        .HasColumnName("total_area");

                    b.HasKey("Id");

                    b.ToTable("real_estates", (string)null);
                });

            modelBuilder.Entity("RealEstateAgency.Domain.Model.RealEstateApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("ApplicationType")
                        .HasColumnType("integer")
                        .HasColumnName("application_type");

                    b.Property<int>("CounterpartyId")
                        .HasColumnType("integer")
                        .HasColumnName("counterparty_id");

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<int>("RealEstateId")
                        .HasColumnType("integer")
                        .HasColumnName("real_estate_id");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartyId");

                    b.HasIndex("RealEstateId");

                    b.ToTable("real_estate_applications", (string)null);
                });

            modelBuilder.Entity("RealEstateAgency.Domain.Model.RealEstateApplication", b =>
                {
                    b.HasOne("RealEstateAgency.Domain.Model.Counterparty", "Counterparty")
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateAgency.Domain.Model.RealEstate", "RealEstate")
                        .WithMany()
                        .HasForeignKey("RealEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counterparty");

                    b.Navigation("RealEstate");
                });
#pragma warning restore 612, 618
        }
    }
}
